### ISSUE TITLE
Get Report SQL

### ISSUE THREAD

**Issue by DanDavies1989** [MicroStrategy/mstrio-py#139] opened 2023-07-05 12:03 UTC
Hey
Can we have the ability to retrieve the SQL view of a report object 
Looks like this functionality is possible using the REST API side of thins but not currently in the Python offering
Apologies if I have missed it however

**Comment by urszulajaczewska** [comment] 2023-07-06 07:37
Hi @DanDavies1989, we will include this functionality with release of Report module which is already in our roadmap. I'll update this issue when the new module is available.

**Comment by DanDavies1989** [comment] 2023-07-06 07:39
Brilliant thank you :)

**Comment by AtharvaGaikwad1** [comment] 2023-09-28 09:36
Hii @DanDavies1989 ,

Till the release you try  this code in Python to get the report SQL from REST API. Initially you'll have to create a connections object in MSTRIO and then later use it for authenticating while creating instance.

```
params = {'offset': 0, 'limit': 5000}
report_id =  'Your Report ID'
body = {}
create_instance = conn.post(
        url=f'{conn.base_url}/api/v2/reports/{report_id}/instances/',
        json=body,
        params=params,
    )

instance = create_instance.json()
instance_id = instance['instanceId']
print(report_id)
print(instance_id)

url1 = (
        f'{conn.base_url}/api/reports/{report_id}/instances/{instance_id}/status'
    )
Instance_Status = conn.get(
        url=url1,
#        params={'closed': None, 'fields': None},
    )
print(Instance_Status)


url2 = (
        f'{conn.base_url}/api/v2/reports/{report_id}/instances/{instance_id}/sqlView'
    )
sql_View = conn.get(
           url=url2,      
    )
sql_expression = sql_View.json()
sql = sql_expression['sqlStatement'] 
print(sql)


```

**Comment by apiotrowskiMicroStrategy** [comment] 2024-10-15 10:28
Duplicate of #126

**Closed by apiotrowskiMicroStrategy** 2024-10-15 10:28 UTC
