### ISSUE TITLE
different version in metadata: '11.2.2.1'

### ISSUE THREAD

**Issue by maq2712** [MicroStrategy/mstrio-py#44] opened 2021-01-09 04:31 UTC
Hi,
I ma facing an Issue while installing the package. Manual download as tar.gz works fine with pip. But online installation fails and pycharm cannot update its packages list. 

pip --version
pip 20.3.3 from d:\python38-32\lib\site-packages\pip (python 3.8)
python --version
Python 3.8.3

Issue is both on Windows and Linux. Following is the error 

ERROR: Requested mstrio-py from https://files.pythonhosted.org/packages/01/1a/a751506dbdcbdcd8d51a84a071cb85e3bda969131ecda5017d13a33ed389/mstrio-py-11.2.2.1.1734.tar.gz#sha256=5439ef651fb97414a5db42bc0d4425b0247ce0942a6a505bb051f927d53002e5 has different version in metadata: '11.2.2.1'

Regards,

**Comment by OskarDuda** [comment] 2021-01-11 14:17
Hi @maq2712, 
thanks for the heads up. The issue was connected to PyPI file name restrictions, which seems to work poorly with naming convention of our package manager.  We are currently working on it and will let you know once it's fixed! :D

Best regards

**Comment by p-kowal** [comment] 2021-01-12 09:29
Hi @maq2712!

The issue is fixed now. You can use pip install mstrio-py, which should bring the newest version of 11.3.0.2. In some cases you need to use the --no-cache-dir parameter as well.

Best,
Piotr

**Closed by p-kowal** 2021-01-12 09:29 UTC
