### ISSUE TITLE
mstrio-py 11.3.12.102 calling alter on objects returned by list_filters throws error

### ISSUE THREAD

**Issue by vladbaja** [MicroStrategy/mstrio-py#172] opened 2024-03-13 11:39 UTC
We just upgraded to mstrio-py==11.3.12.102 and our code was doing:
`filters = list_filters(connection=self._connection, project_name=self._project_name)`

and then at some point something like:
`filters[X].alter(description, qualification)`

which throws:
Object of type _MissingType is not JSON serializable

We upgraded from 11.3.9.103, and in that version the `alter` call worked.

**Comment by mgorskiMicroStrategy** [comment] 2024-03-13 14:07
Hi @vladbaja 
Thanks for logging the issue we will fix it. The problem is caused by list_filters method which when creating Filter class object can't find type of every attribute and replaces it with _MissingType.
Please use this workaround now:
```
filters = list_filters(connection=self._connection, project_name=self._project_name, to_dictionary=True)
for filter in filters:
    filter_obj = Filter(conn, id=filter['id'])
    filter_obj.alter(description, qualification)
```

**Comment by vladbaja** [comment] 2024-03-14 08:52
Thanks! That's the workaround we implemented. We'll remove the workaround once you fix it, because we don't like to query each filter (the ones that need update) twice.

**Comment by apiotrowskiMicroStrategy** [comment] 2024-10-15 11:16
Solution delivered. Closing

**Closed by apiotrowskiMicroStrategy** 2024-10-15 11:16 UTC
